services:
    #  --------------------------------------------
    backend-check-in:
      build:
        context: ./check-in-management
        dockerfile: Dockerfile
      container_name: check-in-management
      depends_on:
        mysql-check-in:
          condition: service_healthy
      ports:
        - "1118:8080"
      networks:
        - red_microservicios
    #  --------------------------------------------
    mysql-check-in:
      build:
        context: ./MySQL
        dockerfile: Dockerfile
      container_name: mysql-check-in
      volumes:
        - ./MySQL/mysql_data:/var/lib/mysql
      ports:
        - "1119:3306"
      networks:
        - red_microservicios
      healthcheck:
        test: [ "CMD","mysql", "-u", "sdgrh", "-psdgrh123*" ]
        interval: 30s
        timeout: 10s
        retries: 5
    #  --------------------------------------------
    adminer-check-in:
      image: adminer
      container_name: adminer-check-in
      depends_on:
        - mysql-check-in
      ports:
        - "1120:8080"
      networks:
        - red_microservicios
  #  --------------------------------------------
networks:
  red_microservicios:
    external: true
